config/routes.rb
Rails.application.routes.draw do
  resources :movies
  get 'home/Index'

  get 'home/ClassInfo'

  get 'home/MidtermExam'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def Index
  end

  def ClassInfo
  end

  def MidtermExam
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:rank, :name, :releaseDate, :distributor, :genre, :mpaa, :grossEarning, :ticketsSold)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/home/ClassInfo.html.erb
<h1>Home#ClassInfo</h1>
<p>
<%=link_to "Index", home_Index_path%>
<%=link_to "Midterm Exam", home_MidtermExam_path%>
</p>

app/views/home/Index.html.erb
<h1>Home#Index</h1>
<p>
<%=link_to "Class Info", home_ClassInfo_path%>
<%=link_to "Midterm Exam", home_MidtermExam_path%>
</p>

app/views/home/MidtermExam.html.erb
<h1>Home#MidtermExam</h1>
<p>
<%=link_to "Class Info", home_ClassInfo_path%>
<%=link_to "Index", home_Index_path%>
</p>

app/views/home/_footer.html.erb
<h1>Footer</h1>

app/views/home/_header.html.erb
<h1>Header</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Midterm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'header'%>
    <%= yield %>
    <%= render 'footer'%>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for(movie) do |f| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rank %>
    <%= f.number_field :rank %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :releaseDate %>
    <%= f.date_select :releaseDate %>
  </div>

  <div class="field">
    <%= f.label :distributor %>
    <%= f.text_field :distributor %>
  </div>

  <div class="field">
    <%= f.label :genre %>
    <%= f.text_field :genre %>
  </div>

  <div class="field">
    <%= f.label :mpaa %>
    <%= f.text_field :mpaa %>
  </div>

  <div class="field">
    <%= f.label :grossEarning %>
    <%= f.number_field :grossEarning %>
  </div>

  <div class="field">
    <%= f.label :ticketsSold %>
    <%= f.number_field :ticketsSold %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<table>
  <thead>
    <tr>
      <th>Rank</th>
      <th>Name</th>
      <th>Releasedate</th>
      <th>Distributor</th>
      <th>Genre</th>
      <th>Mpaa</th>
      <th>Grossearning</th>
      <th>Ticketssold</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.rank %></td>
        <td><%= movie.name %></td>
        <td><%= movie.releaseDate %></td>
        <td><%= movie.distributor %></td>
        <td><%= movie.genre %></td>
        <td><%= movie.mpaa %></td>
        <td><%= movie.grossEarning %></td>
        <td><%= movie.ticketsSold %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rank:</strong>
  <%= @movie.rank %>
</p>

<p>
  <strong>Name:</strong>
  <%= @movie.name %>
</p>

<p>
  <strong>Releasedate:</strong>
  <%= @movie.releaseDate %>
</p>

<p>
  <strong>Distributor:</strong>
  <%= @movie.distributor %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @movie.genre %>
</p>

<p>
  <strong>Mpaa:</strong>
  <%= @movie.mpaa %>
</p>

<p>
  <strong>Grossearning:</strong>
  <%= @movie.grossEarning %>
</p>

<p>
  <strong>Ticketssold:</strong>
  <%= @movie.ticketsSold %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>